### ISSUE TITLE
CMakeLists misses Install statemets

### ISSUE THREAD

**Issue by JimWest** [jveitchmichaelis/edgetpu_ros#2]
Catkin can't install this package correctly because there are no Install statements in the CMakeLists.txt.

**Comment by jveitchmichaelis** [comment]
Thanks for this, I'll fix this week!

**Comment by kindofausername** [comment]
Any progress on that?

**Comment by jveitchmichaelis** [comment]
@arminf82 Apologies, I've been quite busy recently. I should be able to get around to this shortly. If you know what needs fixing, I'm happy to accept a PR though.

BTW I see you work on ai for conservation, anything in particular? (this is also my job, hence why this package exists :))

**Comment by arminf82** [comment]
I can give a try tomorrow, but I am very new to ROS.

@jveitchmichaelis Nothing in particular until now, bussy with my PhD thesis. There are so many possibilities to use AI for automated mapping etc.

**Comment by jveitchmichaelis** [comment]
Should be fixed in https://github.com/jveitchmichaelis/edgetpu_ros/commit/cf43678346a51f895c20876f1717ce2f7a41bbe3, please test and I'll close.
